[tool.ruff]
line-length = 86
exclude = [
    "venv",
    "__pycache__",
    "migrations",
]

[tool.ruff.lint]
select = ["E", "F", "W"]
ignore = ["E203"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
